import{scaleRecipe}from'../domain/quantities/scale.js';
const UNIT_TO_BASE={g:{unit:'g',factor:1},kg:{unit:'g',factor:1000},mL:{unit:'mL',factor:1},L:{unit:'mL',factor:1000}};
const SECTION_RULES=[['Meat & protein',/chicken|beef|lamb|bacon|egg|turkey/i],['Dairy & chilled',/milk|yoghurt|cream|butter|cheese|feta|cottage/i],['Fruit & vegetables',/apple|pear|mandarin|strawberr|potato|pumpkin|carrot|broccoli|spinach|leek|mushroom|cabbage|onion|corn|peas|beans|garlic|ginger|lemon|banana|blueberr|pineapple/i],['Bakery',/bread|pastry|wrap/i],['Pantry',/oats|rice|barley|flour|noodle|stock|soy|oil|honey|sugar|mustard|sauce|spice|paprika|cinnamon|thyme|oregano|whey|protein|chia|walnut|peanut|sesame|curry|cornflour/i]];
export function sectionForIngredient(name){return SECTION_RULES.find(([,p])=>p.test(name))?.[0]||'Other'}
export function parseQuantity(value){const m=String(value).trim().match(/^(\d+(?:\.\d+)?)\s*(kg|g|mL|L)$/);return m?{amount:+m[1],unit:m[2]}:null}
function formatQuantity(amount,unit){if(unit==='g'&&amount>=1000)return`${Number((amount/1000).toFixed(2))} kg`;if(unit==='mL'&&amount>=1000)return`${Number((amount/1000).toFixed(2))} L`;return`${Number(amount.toFixed(1))} ${unit}`}
export function normaliseSlot(slot,recipes){if(!slot)return null;if(typeof slot==='string'){const recipe=recipes.find(r=>r.id===slot);return recipe?{id:slot,servings:recipe.servings||5}:null}return{id:slot.id,servings:Number(slot.servings)||5}}
export function slotRecipe(slot,recipes){const normal=normaliseSlot(slot,recipes);if(!normal)return null;const recipe=recipes.find(r=>r.id===normal.id);return recipe?scaleRecipe(recipe,normal.servings):null}
export function consolidateIngredients(selectedRecipes){const grouped=new Map(),loose=[];for(const recipe of selectedRecipes){for(const item of recipe.ingredients||[]){const[name,quantity]=item,parsed=parseQuantity(quantity);if(!parsed||!UNIT_TO_BASE[parsed.unit]){loose.push({name,quantity,section:sectionForIngredient(name)});continue}const c=UNIT_TO_BASE[parsed.unit],key=`${name.toLowerCase()}::${c.unit}`,current=grouped.get(key)||{name,amount:0,unit:c.unit};current.amount+=parsed.amount*c.factor;grouped.set(key,current)}}return[...Array.from(grouped.values()).map(x=>({name:x.name,quantity:formatQuantity(x.amount,x.unit),section:sectionForIngredient(x.name)})),...loose].sort((a,b)=>a.section.localeCompare(b.section)||a.name.localeCompare(b.name))}
export function plannedRecipeIds(plan){return Array.from(new Set(Object.values(plan).map(x=>typeof x==='string'?x:x?.id).filter(Boolean)))}
export function plannedRecipeSlots(plan,recipes){const unique=new Map();for(const value of Object.values(plan)){const slot=normaliseSlot(value,recipes);if(slot)unique.set(`${slot.id}:${slot.servings}`,slot)}return[...unique.values()]}
export function calculateDayTotals(slots,recipes,extraSnacks=[]){const base={calories:0,protein:0,carbs:0,fat:0,meals:0};for(const slot of slots){const recipe=slotRecipe(slot,recipes);if(!recipe)continue;base.calories+=recipe.calories;base.protein+=recipe.protein;base.carbs+=recipe.carbs;base.fat+=recipe.fat;base.meals++}for(const snack of extraSnacks){base.calories+=snack.calories;base.protein+=snack.protein;base.carbs+=snack.carbs;base.fat+=snack.fat}return base}
export function calculateWeekSummary(plan,recipes,days,meals,snacksByDay={}){const complete=days.map(day=>({day,slots:meals.map(meal=>plan[`${day}-${meal}`]).filter(Boolean)})).filter(x=>x.slots.length===meals.length).map(({day,slots})=>calculateDayTotals(slots,recipes,snacksByDay[day]||[]));if(!complete.length)return{completeDays:0,averages:{calories:0,protein:0,carbs:0,fat:0}};const totals=complete.reduce((s,d)=>({calories:s.calories+d.calories,protein:s.protein+d.protein,carbs:s.carbs+d.carbs,fat:s.fat+d.fat}),{calories:0,protein:0,carbs:0,fat:0});return{completeDays:complete.length,averages:Object.fromEntries(Object.entries(totals).map(([k,v])=>[k,Number((v/complete.length).toFixed(1))]))}}
