import test from'node:test';import assert from'node:assert/strict';
import{createRecord,updateRecord,deleteRecord,isTombstone,validateRecord}from'../src/data/repositories/records.js';
import{enqueue,markFailure,dueItems,drainQueue}from'../src/data/sync/queue.js';
import{detectConflict,resolveConflict}from'../src/data/sync/conflicts.js';
import{createAccountExport,validateAccountExport,importPreview}from'../src/data/sync/portability.js';
import{prepareInitialSync,recordsFromSnapshot,runSyncCycle,snapshotFromRecords}from'../src/data/sync/engine.js';
import{cloudConfigured}from'../src/data/sync/supabase.js';

function fakeRemote(seed=[]){const records=new Map(seed.map(x=>[x.id,structuredClone(x)]));return{async listRecords(){return[...records.values()].map(x=>structuredClone(x))},async push(operation){const current=records.get(operation.recordId);if((current?.version||0)!==(operation.baseVersion||0)){const error=new Error('version conflict');error.code='VERSION_CONFLICT';error.current=current;throw error}records.set(operation.recordId,structuredClone(operation.record))},size(){return records.size},get(id){return records.get(id)}}}

test('records carry versions and tombstones',()=>{const one=createRecord('planner','week',{a:1},'2026-07-29T00:00:00.000Z'),two=updateRecord(one,{a:2},'2026-07-29T00:01:00.000Z'),gone=deleteRecord(two);assert.equal(two.version,2);assert.equal(isTombstone(gone),true);assert.deepEqual(validateRecord(one),[])});
test('queue is idempotent and bounded failures become stuck',()=>{const op={recordId:'x',version:1,type:'put'},q=enqueue(enqueue([],op),op);assert.equal(q.length,1);let item=q[0];for(let i=0;i<5;i++)item=markFailure(item,'offline',0);assert.equal(item.state,'stuck')});
test('queue drains successful operations without duplication',async()=>{const q=enqueue([],{recordId:'x',version:1,type:'put'});assert.equal(dueItems(q,q[0].nextAttemptAt).length,1);assert.deepEqual(await drainQueue(q,async()=>{},Date.parse(q[0].nextAttemptAt)),[])});
test('independent fields auto merge despite clock skew',()=>{const base=createRecord('notes','n',{text:'a',tag:'x'},'2026-07-29T05:00:00.000Z'),local={...base,version:2,updatedAt:'2026-07-29T04:00:00.000Z',data:{text:'b',tag:'x'}},remote={...base,version:2,updatedAt:'2026-07-29T06:00:00.000Z',data:{text:'a',tag:'y'}};const result=detectConflict(base,local,remote);assert.equal(result.conflict,false);assert.deepEqual(result.record.data,{text:'b',tag:'y'})});
test('overlapping fields preserve both versions until resolution',()=>{const base=createRecord('notes','n',{text:'a'}),local={...base,version:2,data:{text:'b'}},remote={...base,version:2,data:{text:'c'}};const conflict=detectConflict(base,local,remote);assert.equal(conflict.conflict,true);assert.equal(conflict.preserved.length,2);assert.equal(resolveConflict(conflict,{text:'local'}).data.text,'b')});
test('offline-created records synchronize once without duplication',async()=>{const remote=fakeRemote(),local=[createRecord('planner','root',{Monday:'B1'},'2026-07-29T00:00:00.000Z')],prepared=prepareInitialSync(local,[],'replace-cloud','2026-07-29T00:00:00.000Z');let state=await runSyncCycle(prepared,remote,Date.parse('2026-07-29T00:01:00.000Z'));state=await runSyncCycle(state,remote,Date.parse('2026-07-29T00:02:00.000Z'));assert.equal(remote.size(),1);assert.equal(state.queue.length,0);assert.deepEqual(snapshotFromRecords(state.records).planner,{Monday:'B1'})});
test('two-device overlapping edits become a visible conflict',async()=>{const base=createRecord('notes','root',{B1:'original'},'2026-07-29T00:00:00.000Z'),remote=fakeRemote([base]),deviceA={...base,version:2,updatedAt:'2026-07-29T01:00:00.000Z',data:{B1:'device A'}},deviceB={...base,version:2,updatedAt:'2026-07-29T01:30:00.000Z',data:{B1:'device B'}};let a=await runSyncCycle({baseRecords:[base],records:[deviceA],queue:[]},remote,Date.parse('2026-07-29T02:00:00.000Z'));a=await runSyncCycle(a,remote,Date.parse('2026-07-29T02:01:00.000Z'));const b=await runSyncCycle({baseRecords:[base],records:[deviceB],queue:[]},remote,Date.parse('2026-07-29T02:02:00.000Z'));assert.equal(b.conflicts.length,1);assert.equal(b.conflicts[0].preserved.length,2)});
test('snapshot records increment only when local data changes',()=>{const first=recordsFromSnapshot({planner:{a:1}},'2026-07-29T00:00:00.000Z'),same=recordsFromSnapshot({planner:{a:1}},'2026-07-29T01:00:00.000Z',first),changed=recordsFromSnapshot({planner:{a:2}},'2026-07-29T02:00:00.000Z',first);assert.equal(same.find(x=>x.collection==='planner').version,1);assert.equal(changed.find(x=>x.collection==='planner').version,2)});
test('account export validates and previews clean restore',()=>{const records=[createRecord('planner','week',{a:1})],value=createAccountExport({profile:{},records,consents:[],integrations:[]});assert.equal(validateAccountExport(value).valid,true);assert.deepEqual(importPreview([],value),{valid:true,errors:[],counts:{records:1,collections:1},newRecords:1,updates:0,conflicts:0})});
test('local-only mode requires no provider configuration',()=>assert.equal(cloudConfigured({}),false));
