export const weeklyRecipes202608 = [
  {
    id: 'B6',
    slug: 'b6-strawberry-jam-doughnut-pancake-pots',
    title: 'Strawberry Jam Doughnut Pancake Pots',
    meal: 'Breakfast',
    description: 'Fluffy vanilla pancake pieces layered with reduced strawberry-chia jam, cinnamon sugar and cold vanilla protein yoghurt. The pancakes remain tender after reheating rather than becoming rubbery or custard-like.',
    servings: 5,
    prep: '25 min',
    cook: '25–30 min',
    equipment: 'Two large non-stick frying pans or one frying pan used in batches; small saucepan; mixing bowls; five 700 mL meal-prep containers',
    initialEstimate: { label: 'Initial estimate', value: '525 kcal', detail: '43 P · 66 C · 10 F' },
    calculatedActual: { label: 'Calculated actual / serving', value: '547 kcal', detail: '44.5 P · 63.4 C · 11.0 F' },
    difference: { label: 'Difference', value: '+22 kcal', detail: '+1.5 P · -2.6 C · +1.0 F' },
    calories: 547.09,
    protein: 44.513,
    carbs: 63.377,
    fat: 11.025,
    ingredients: [
      ['Self-raising flour', '250 g'],
      ['Vanilla whey protein', '100 g'],
      ['Whole egg, without shell', '200 g (about 4 large eggs)'],
      ['Light milk', '400 mL'],
      ['Unsalted butter', '15 g, melted'],
      ['Vanilla extract', '10 mL'],
      ['Baking powder', '10 g'],
      ['Strawberries, hulled', '600 g'],
      ['Chia seeds', '20 g'],
      ['Caster sugar', '25 g'],
      ['Lemon juice', '30 mL'],
      ['High-protein plain yoghurt', '750 g'],
      ['Ground cinnamon', '4 g'],
      ['Fine salt', '2 g']
    ],
    method: [
      'Make the jam first. Roughly chop the strawberries and place them in a saucepan with 15 g of the sugar and the lemon juice. Cook over medium heat for 8–10 minutes, stirring and crushing occasionally, until glossy and reduced but still containing small fruit pieces.',
      'Stir the chia seeds into the hot strawberries, simmer for 1 minute, then remove from the heat. The jam should look slightly loose while hot; it thickens as it cools. Transfer to a shallow container and refrigerate.',
      'For the pancake batter, whisk the flour, 70 g whey, baking powder, 10 g remaining sugar, cinnamon and salt. In a second bowl whisk the eggs, milk, vanilla and 10 g melted butter.',
      'Fold wet ingredients into dry only until the flour disappears. The batter should be thick but pourable and fall from the spoon in a broad ribbon. Rest for 8 minutes; add 15–30 mL extra water only if it becomes too stiff to spread.',
      'Heat a large non-stick frying pan over medium-low heat and brush with the remaining 5 g butter. Cook pancakes in 8–10 cm rounds for about 2 minutes, until bubbles hold open and the underside is golden. Turn once and cook 60–90 seconds. Avoid pressing them down.',
      'Cool the pancakes on a rack, then tear or cut into 3 cm pieces. Mix the remaining 30 g whey into the yoghurt with 30–50 mL water until smooth and spoonable.',
      'Divide pancake pieces among five containers. Pack the jam and yoghurt in separate compartments or small tubs so the pancakes do not become soggy. Add the cinnamon-sugar effect by dusting each warm serving with a small pinch of cinnamon from the measured amount.'
    ],
    storage: 'Refrigerate pancake pieces, jam and yoghurt separately for up to 5 days. Freeze pancake pieces only for up to 2 months, separated with baking paper. Do not freeze the yoghurt or finished assembled pots.',
    reheat: 'Microwave one portion of pancake pieces for 45–60 seconds at 70% power, rest for 20 seconds, then add the cold jam and yoghurt. For better edges, air-fry the pancake pieces at 160°C for 3–4 minutes.',
    upgrade: 'Warm the jam with finely grated lemon zest and add a tiny pinch of flaky salt immediately before serving. These are negligible only as light garnishes; larger additions require recalculation.',
    textureCheck: 'The pancakes should be fluffy and clearly bread-like, not eggy. The jam should be spoonable rather than watery, and the yoghurt should sit as a cold creamy layer rather than soaking the pancakes during storage.',
    batchMacros: { calories: 2735.45, protein: 222.565, carbs: 316.885, fat: 55.125 },
    sanity: 'Calorie cross-check from protein × 4 + carbohydrate × 4 + fat × 9: 2654 kcal for the batch. Label/database energy differs by +3.0%, primarily from fibre, organic acids and rounding.',
    assumption: 'Self-raising flour 350 kcal/10 P/72 C/1 F per 100 g; vanilla whey 392 kcal/76 P/8 C/6 F; light milk 45 kcal/3.4 P/4.8 C/1.3 F; high-protein yoghurt 62 kcal/10 P/4 C/0.3 F; raw edible strawberry weight. Brand or protein-powder changes require complete recalculation.',
    status: 'Ingredient-verified macros',
    tags: ['Meal prep', 'Brisbane winter', 'Strawberries', 'Pancakes', '5 servings']
  },
  {
    id: 'L16',
    slug: 'l16-beef-enchilada-rice-bowls',
    title: 'Beef Enchilada Rice Bowls',
    meal: 'Lunch',
    description: 'Lean smoky beef, black beans, corn and capsicum in a thick homemade enchilada sauce with rice, melted cheese and lime protein yoghurt.',
    servings: 5,
    prep: '25 min',
    cook: '35–40 min',
    equipment: 'Large heavy frying pan or shallow casserole; medium saucepan with lid; roasting tray; five 1 L meal-prep containers',
    initialEstimate: { label: 'Initial estimate', value: '735 kcal', detail: '57 P · 68 C · 27 F' },
    calculatedActual: { label: 'Calculated actual / serving', value: '684 kcal', detail: '59.8 P · 65.8 C · 17.5 F' },
    difference: { label: 'Difference', value: '-51 kcal', detail: '+2.8 P · -2.2 C · -9.5 F' },
    calories: 684.12,
    protein: 59.812,
    carbs: 65.764,
    fat: 17.49,
    ingredients: [
      ['Lean beef mince, raw', '750 g, approximately 5% fat'],
      ['Long-grain rice, dry weight', '200 g'],
      ['Black beans, drained weight', '300 g'],
      ['Corn kernels, drained or frozen weight', '200 g'],
      ['Red capsicum, raw edible weight', '400 g, diced'],
      ['Brown onion, raw edible weight', '200 g, diced'],
      ['Passata', '500 g'],
      ['Tomato paste', '60 g'],
      ['Garlic', '20 g, finely grated'],
      ['Light tasty cheese', '150 g, grated'],
      ['High-protein plain yoghurt', '300 g'],
      ['Extra-virgin olive oil', '15 g'],
      ['Lime juice', '50 mL'],
      ['Ground cumin', '8 g'],
      ['Smoked paprika', '6 g'],
      ['Dried oregano', '3 g'],
      ['Mild chilli powder', '3 g'],
      ['Fine salt', '6 g'],
      ['Black pepper', '2 g']
    ],
    method: [
      'Rinse the rice until the water is mostly clear. Cook the 200 g dry rice according to the packet absorption method, then spread it on a tray for 5 minutes so steam can escape. This prevents clumping after refrigeration.',
      'Heat the oil in a large frying pan over medium-high heat. Add the onion and capsicum with a pinch of the measured salt. Cook for 7–9 minutes until softened and beginning to brown at the edges.',
      'Add the beef mince. Break it into small irregular pieces and cook for 7–8 minutes until no pink remains and some pieces have browned. Do not continuously stir or the beef will steam.',
      'Add garlic, cumin, paprika, oregano and chilli powder. Cook for 45 seconds. Stir in the tomato paste and cook for another 90 seconds until it darkens slightly.',
      'Add passata and 100 mL water. Simmer uncovered for 8–10 minutes until the sauce coats the beef rather than pooling underneath it. Fold through the drained black beans and corn and heat for 2 minutes. Season with the remaining salt and pepper.',
      'Mix the yoghurt with the lime juice and 20–30 mL water until it forms a thick drizzle. Divide rice, beef mixture and cheese evenly among five containers, keeping the lime yoghurt separate.',
      'Cool uncovered until no longer steaming, then seal and refrigerate. Add the cheese on top of the hot component so it melts during reheating.'
    ],
    storage: 'Refrigerate for up to 5 days. Keep lime yoghurt separately. Freeze the rice-and-beef portion for up to 2 months; thaw overnight in the refrigerator before reheating.',
    reheat: 'Sprinkle 15 mL water over the rice, cover loosely and microwave for 2½–3½ minutes, stirring once, until the centre is piping hot. Rest for 1 minute and add lime yoghurt afterward.',
    upgrade: 'Char the capsicum under a grill before dicing, or finish with fresh coriander and pickled jalapeño. Measured avocado, tortilla chips or extra cheese materially change macros and require recalculation.',
    textureCheck: 'The beef mixture should be thick and glossy with separate browned beef pieces. Rice should remain distinct, and the cold lime yoghurt should provide contrast rather than disappearing into a watery sauce.',
    batchMacros: { calories: 3420.6, protein: 299.06, carbs: 328.82, fat: 87.45 },
    sanity: 'Calorie cross-check from protein × 4 + carbohydrate × 4 + fat × 9: 3299 kcal for the batch. Label/database energy differs by +3.6%, primarily from fibre, organic acids and rounding.',
    assumption: 'Beef mince is raw 5% fat at 137 kcal/21.4 P/0 C/5 F per 100 g; rice is calculated from dry weight; beans and corn use drained weights; light cheese 280 kcal/32 P/1 C/16 F; high-protein yoghurt 62 kcal/10 P/4 C/0.3 F. Different beef fat percentage, rice, cheese or yoghurt requires complete recalculation.',
    status: 'Ingredient-verified macros',
    tags: ['Meal prep', 'Brisbane winter', 'Beef', 'Mexican-inspired', 'Rice bowl', '5 servings']
  },
  {
    id: 'D6',
    slug: 'd6-jamaican-jerk-chicken-coconut-rice-pineapple-slaw',
    title: 'Jamaican-Inspired Jerk Chicken with Coconut Rice and Pineapple Slaw',
    meal: 'Dinner',
    description: 'Caramelised jerk-spiced chicken thigh with coconut rice and beans, roasted corn and a bright pineapple-cabbage slaw with lime yoghurt.',
    servings: 5,
    prep: '35 min plus marinating',
    cook: '40–45 min',
    equipment: 'Large roasting tray; medium saucepan with lid; large mixing bowl; blender or mortar optional; five 1.2 L meal-prep containers',
    initialEstimate: { label: 'Initial estimate', value: '885 kcal', detail: '65 P · 93 C · 27 F' },
    calculatedActual: { label: 'Calculated actual / serving', value: '899 kcal', detail: '61.0 P · 81.5 C · 35.6 F' },
    difference: { label: 'Difference', value: '+14 kcal', detail: '-4.0 P · -11.5 C · +8.6 F' },
    calories: 898.736,
    protein: 61.002,
    carbs: 81.524,
    fat: 35.612,
    ingredients: [
      ['Skinless chicken thigh fillets, raw', '1.1 kg, trimmed'],
      ['Long-grain rice, dry weight', '210 g'],
      ['Light coconut milk', '400 mL'],
      ['Kidney beans, drained weight', '300 g'],
      ['Pineapple flesh', '400 g, diced'],
      ['Green cabbage, raw edible weight', '500 g, finely shredded'],
      ['Corn kernels', '250 g'],
      ['High-protein plain yoghurt', '300 g'],
      ['Extra-virgin olive oil', '47 g'],
      ['Reduced-salt soy sauce', '50 mL'],
      ['Brown sugar', '30 g'],
      ['Lime juice', '100 mL'],
      ['Garlic', '30 g'],
      ['Fresh ginger', '30 g'],
      ['Spring onion', '100 g'],
      ['Ground allspice', '8 g'],
      ['Dried thyme', '5 g'],
      ['Smoked paprika', '5 g'],
      ['Ground cinnamon', '2 g'],
      ['Ground nutmeg', '1 g'],
      ['Cayenne pepper', '2–4 g, to taste'],
      ['Fine salt', '5 g'],
      ['Black pepper', '2 g']
    ],
    method: [
      'Blend or finely crush the garlic, ginger, half the spring onion, soy sauce, brown sugar, 60 mL lime juice, allspice, thyme, paprika, cinnamon, nutmeg, cayenne, black pepper and 27 g olive oil into a rough jerk paste.',
      'Pat the chicken dry, trim obvious fat and cut each thigh into two or three large pieces. Coat with the jerk paste and marinate for at least 30 minutes or up to 24 hours in the refrigerator.',
      'Heat the oven to 220°C fan-forced. Spread the chicken on a large lined roasting tray with space between pieces. Roast for 20–25 minutes, turning once, until browned at the edges and the thickest pieces reach at least 74°C. Rest for 8 minutes before slicing.',
      'Meanwhile, rinse the rice. Add rice, coconut milk, 120 mL water and 2 g measured salt to a saucepan. Bring just to a simmer, cover and cook on very low heat for 12 minutes. Remove from heat and stand covered for 10 minutes. Fold through the drained kidney beans and fluff gently.',
      'Toss the corn with 10 g olive oil and roast on a second area of the chicken tray or a separate tray for 12–15 minutes until lightly blistered.',
      'For the slaw, combine cabbage, pineapple and remaining spring onion. Mix yoghurt with the remaining 40 mL lime juice, remaining 10 g olive oil and remaining salt. Keep the dressing separate until serving so the cabbage stays crisp.',
      'Divide coconut rice and beans, jerk chicken and corn among five containers. Pack the undressed slaw and lime yoghurt separately. Spoon any measured tray juices over the chicken rather than discarding them.'
    ],
    storage: 'Refrigerate cooked chicken, rice and corn for up to 5 days. Store slaw and dressing separately. Freeze chicken and rice for up to 2 months; do not freeze the dressed slaw.',
    reheat: 'Add 15–20 mL water to the rice, cover loosely and microwave for 2½–3½ minutes, stirring once. Heat until the chicken and rice are piping hot, rest for 1 minute, then add cold slaw and dressing.',
    upgrade: 'Finish the reheated chicken under a hot grill for 2 minutes to restore charred edges. Fresh coriander, extra lime zest or a very small amount of Scotch bonnet may be added as negligible garnishes; additional oil or sauce requires recalculation.',
    textureCheck: 'Chicken should have browned, slightly sticky edges but remain juicy. Coconut rice must be fluffy rather than wet, and the pineapple slaw should stay crisp and bright through separate storage.',
    batchMacros: { calories: 4493.68, protein: 305.01, carbs: 407.62, fat: 178.06 },
    sanity: 'Calorie cross-check from protein × 4 + carbohydrate × 4 + fat × 9: 4453 kcal for the batch. Label/database energy differs by +0.9%, primarily from fibre, organic acids and rounding.',
    assumption: 'Chicken thigh is raw, skinless and trimmed at 154 kcal/19 P/0 C/8.5 F per 100 g; rice is calculated from dry weight; coconut milk 70 kcal/0.8 P/2.2 C/6.5 F per 100 mL; kidney beans use drained weight; yoghurt 62 kcal/10 P/4 C/0.3 F. Chicken cut, coconut milk, retained oil and bean brand materially affect macros and require complete recalculation.',
    status: 'Ingredient-verified macros',
    tags: ['Meal prep', 'Brisbane winter', 'Chicken thigh', 'Jerk-inspired', 'Coconut rice', '5 servings']
  }
];
