import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{HashRouter,Link,NavLink,Route,Routes}from'react-router-dom';
import{recipes,targets}from'./data';
import{readStored,writeStored}from'./data/storage';
import{ErrorBoundary,EmptyState}from'./app/ErrorBoundary';
import{PwaStatus}from'./app/PwaStatus';
import{DataTools}from'./features/profile/DataTools';
import{AccountPage}from'./features/account/AccountPage';
import{ScaledRecipe}from'./features/recipes/ScaledRecipe';
import{RecipeEditor}from'./features/recipes/editor/RecipeEditor';
import{PlannerPage}from'./features/planner/PlannerPage';
import{ScaledShopping}from'./features/shopping/ScaledShopping';
import{PantryPage}from'./features/pantry/PantryPage';
import{calculateWeekSummary}from'./lib/planning';
import'./styles.css';
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],MEALS=['Breakfast','Lunch','Dinner'];
function Layout(){return <div className="shell"><aside><Link className="brand" to="/"><span className="mark">P</span><span><b>PrepPilot</b><small>Meal prep, dialled in.</small></span></Link><nav aria-label="Primary navigation"><NavLink to="/">Dashboard</NavLink><NavLink to="/recipes">Recipes</NavLink><NavLink to="/recipe-engine">Recipe engine</NavLink><NavLink to="/planner">Planner</NavLink><NavLink to="/shopping-list">Shopping list</NavLink><NavLink to="/pantry">Pantry & costs</NavLink><NavLink to="/account">Account & sync</NavLink><NavLink to="/data-tools">Data tools</NavLink></nav><div className="target-note"><span>Base daily target</span><b>{targets.calories.toLocaleString('en-AU')} kcal</b><small>≥{targets.protein} P · {targets.carbs} C · {targets.fat} F</small></div></aside><main><PwaStatus/><Routes><Route path="/" element={<Dashboard/>}/><Route path="/recipes" element={<Library/>}/><Route path="/recipes/:slug" element={<ScaledRecipe/>}/><Route path="/recipe-engine" element={<RecipeEditor/>}/><Route path="/planner" element={<PlannerPage/>}/><Route path="/shopping-list" element={<ScaledShopping/>}/><Route path="/pantry" element={<PantryPage/>}/><Route path="/account" element={<AccountPage/>}/><Route path="/data-tools" element={<DataTools/>}/><Route path="*" element={<EmptyState title="That page wandered off" action={<Link className="primary" to="/">Back home</Link>}>The link may be outdated.</EmptyState>}/></Routes></main></div>}
function Dashboard(){const planner=readStored('planner',{}),custom=readStored('customRecipes',[]),pantry=readStored('pantry',[]),sync=readStored('syncSettings',{mode:'local-only'}),queue=readStored('syncQueue',[]),summary=calculateWeekSummary(planner,recipes,DAYS,MEALS),assigned=Object.values(planner).filter(Boolean).length;return <><header className="hero"><p className="eyebrow">Local-first meal-prep operating system</p><h1>Your data works here first.</h1><p>Plan, cook and shop offline. Optional account sync adds cross-device access without making the cloud a prerequisite.</p><div className="actions"><Link className="primary" to="/planner">Plan this week</Link><Link className="secondary" to="/account">Account & sync</Link></div></header><section className="target-grid">{[['Calories',targets.calories,'kcal'],['Protein',targets.protein,'g minimum'],['Carbohydrate',targets.carbs,'g base'],['Fat',targets.fat,'g']].map(([l,v,u])=><article key={l}><span>{l}</span><b>{v}</b><small>{u}</small></article>)}</section><section className="summary-grid"><article><span>Meals planned</span><b>{assigned}</b><small>of 21 slots</small></article><article><span>Pantry items</span><b>{pantry.filter(x=>!x.archived).length}</b><small>available for deductions</small></article><article><span>Data mode</span><b>{sync.mode==='cloud'?'Cloud':'Local-only'}</b><small>{queue.length} queued sync operation{queue.length===1?'':'s'}</small></article></section><div className="notice"><b>No silent data loss</b><p>Concurrent overlapping edits preserve both versions for review. Local-only mode remains fully functional without authentication or network access.</p></div></>}
function Library(){const[query,setQuery]=useState(''),[meal,setMeal]=useState('All'),[onlyFav,setOnlyFav]=useState(false),[favourites,setFavourites]=useState(()=>readStored('favourites',[]));const filtered=useMemo(()=>recipes.filter(r=>(meal==='All'||r.meal===meal)&&(!onlyFav||favourites.includes(r.id))&&`${r.title} ${r.description} ${r.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[query,meal,onlyFav,favourites]);function fav(id){const next=favourites.includes(id)?favourites.filter(x=>x!==id):[...favourites,id];setFavourites(next);writeStored('favourites',next)}return <><header className="page-head"><p className="eyebrow">Recipe library</p><h1>Choose and scale your prep.</h1><p>Built-in recipes remain immutable ingredient-verified sources. Create or clone custom versions in the Recipe engine.</p></header><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search recipes…"/><div className="chips">{['All',...MEALS].map(x=><button className={meal===x?'active':''} onClick={()=>setMeal(x)} key={x}>{x}</button>)}<button className={onlyFav?'active':''} onClick={()=>setOnlyFav(!onlyFav)}>★ Favourites</button></div></div>{filtered.length?<div className="cards">{filtered.map(r=><Link className="card" to={`/recipes/${r.slug}`} key={r.id}><div className={`art ${r.meal.toLowerCase()}`}><button className="favourite" onClick={e=>{e.preventDefault();fav(r.id)}} aria-label="Toggle favourite">{favourites.includes(r.id)?'★':'☆'}</button><span>{r.id}</span></div><div className="card-body"><div className="meta"><span>{r.meal}</span><span>Ingredient-verified</span></div><h3>{r.title}</h3><p>{r.description}</p><div className="macros"><b>{r.calories} kcal</b><span>{r.protein} P</span><span>{r.carbs} C</span><span>{r.fat} F</span></div></div></Link>)}</div>:<EmptyState title="No recipes match">Clear the search or change filters.</EmptyState>}</>}
createRoot(document.getElementById('root')).render(<React.StrictMode><ErrorBoundary><HashRouter><Layout/></HashRouter></ErrorBoundary></React.StrictMode>);
