import React,{Suspense,lazy,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{HashRouter,Link,NavLink,Route,Routes}from'react-router-dom';
import{recipes,targets}from'./data';
import{readStored,writeStored}from'./data/storage';
import{ErrorBoundary,EmptyState}from'./app/ErrorBoundary';
import{PwaStatus}from'./app/PwaStatus';
import{RouteAccessibility,RouteLoading,SkipLink}from'./components/RouteAccessibility';
import'./styles.css';
import'./phase7.css';

const lazyNamed=(loader,name)=>lazy(()=>loader().then(module=>({default:module[name]})));
const DataTools=lazyNamed(()=>import('./features/profile/DataTools'),'DataTools');
const AccountPage=lazyNamed(()=>import('./features/account/AccountPage'),'AccountPage');
const AiPlannerPage=lazyNamed(()=>import('./features/ai/AiPlannerPage'),'AiPlannerPage');
const ScaledRecipe=lazyNamed(()=>import('./features/recipes/ScaledRecipe'),'ScaledRecipe');
const RecipeEditor=lazyNamed(()=>import('./features/recipes/editor/RecipeEditor'),'RecipeEditor');
const PlannerPage=lazyNamed(()=>import('./features/planner/PlannerPage'),'PlannerPage');
const ScaledShopping=lazyNamed(()=>import('./features/shopping/ScaledShopping'),'ScaledShopping');
const PantryPage=lazyNamed(()=>import('./features/pantry/PantryPage'),'PantryPage');
const HealthPage=lazyNamed(()=>import('./features/health/HealthPage'),'HealthPage');

const MEALS=['Breakfast','Lunch','Dinner'];
const NAV=[['/','Dashboard'],['/recipes','Recipes'],['/recipe-engine','Recipe engine'],['/planner','Planner'],['/ai-planner','AI assistant'],['/shopping-list','Shopping list'],['/pantry','Pantry & costs'],['/health','Training & progress'],['/account','Account & sync'],['/data-tools','Data tools']];

function Layout(){return <><SkipLink/><div className="shell"><aside aria-label="Application sidebar"><Link className="brand" to="/"><span className="mark" aria-hidden="true">P</span><span><b>PrepPilot</b><small>Meal prep, dialled in.</small></span></Link><nav aria-label="Primary navigation">{NAV.map(([to,label])=><NavLink key={to} end={to==='/'} to={to}>{label}</NavLink>)}</nav><div className="target-note"><span>Base daily target</span><b>{targets.calories.toLocaleString('en-AU')} kcal</b><small>≥{targets.protein} P · {targets.carbs} C · {targets.fat} F</small></div></aside><main id="main-content" tabIndex="-1"><PwaStatus/><RouteAccessibility/><Suspense fallback={<RouteLoading/>}><Routes><Route path="/" element={<Dashboard/>}/><Route path="/recipes" element={<Library/>}/><Route path="/recipes/:slug" element={<ScaledRecipe/>}/><Route path="/recipe-engine" element={<RecipeEditor/>}/><Route path="/planner" element={<PlannerPage/>}/><Route path="/ai-planner" element={<AiPlannerPage/>}/><Route path="/shopping-list" element={<ScaledShopping/>}/><Route path="/pantry" element={<PantryPage/>}/><Route path="/health" element={<HealthPage/>}/><Route path="/account" element={<AccountPage/>}/><Route path="/data-tools" element={<DataTools/>}/><Route path="*" element={<EmptyState title="That page wandered off" action={<Link className="primary" to="/">Back home</Link>}>The link may be outdated.</EmptyState>}/></Routes></Suspense></main></div></>}
function Dashboard(){const planner=readStored('planner',{}),pantry=readStored('pantry',[]),activities=readStored('activities',[]),assigned=Object.values(planner).filter(Boolean).length;return <><header className="hero"><p className="eyebrow">Local-first nutrition and training</p><h1>Plan meals around the work that matters.</h1><p>Verified recipes, transparent nutrition calculations and optional integrations stay usable even when external services are unavailable.</p><div className="actions"><Link className="primary" to="/planner">Plan this week</Link><Link className="secondary" to="/health">Review training</Link></div></header><section className="target-grid" aria-label="Daily nutrition targets">{[['Calories',targets.calories,'kcal'],['Protein',targets.protein,'g minimum'],['Carbohydrate',targets.carbs,'g base'],['Fat',targets.fat,'g']].map(([label,value,unit])=><article key={label}><span>{label}</span><b>{value}</b><small>{unit}</small></article>)}</section><section className="summary-grid" aria-label="Application summary"><article><span>Meals planned</span><b>{assigned}</b><small>of 21 slots</small></article><article><span>Pantry items</span><b>{pantry.filter(item=>!item.archived).length}</b><small>available for deductions</small></article><article><span>Training records</span><b>{activities.length}</b><small>manual or attributed imports</small></article></section><div className="notice"><b>Deterministic rules stay authoritative</b><p>AI and integrations may suggest or import information, but they cannot verify recipes, reduce the protein floor or silently alter your targets.</p></div></>}
function Library(){const[query,setQuery]=useState(''),[meal,setMeal]=useState('All'),[onlyFav,setOnlyFav]=useState(false),[favourites,setFavourites]=useState(()=>readStored('favourites',[]));const filtered=useMemo(()=>recipes.filter(recipe=>(meal==='All'||recipe.meal===meal)&&(!onlyFav||favourites.includes(recipe.id))&&`${recipe.title} ${recipe.description} ${recipe.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[query,meal,onlyFav,favourites]);function toggleFavourite(id){const next=favourites.includes(id)?favourites.filter(value=>value!==id):[...favourites,id];setFavourites(next);writeStored('favourites',next)}return <><header className="page-head"><p className="eyebrow">Recipe library</p><h1>Choose and scale your prep.</h1><p>Built-in recipes remain immutable ingredient-verified sources. Create or clone custom versions in the Recipe engine.</p></header><div className="toolbar"><label className="field-label">Search recipes<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Recipe name or ingredient"/></label><div className="chips" aria-label="Recipe filters">{['All',...MEALS].map(value=><button type="button" className={meal===value?'active':''} aria-pressed={meal===value} onClick={()=>setMeal(value)} key={value}>{value}</button>)}<button type="button" className={onlyFav?'active':''} aria-pressed={onlyFav} onClick={()=>setOnlyFav(!onlyFav)}>★ Favourites</button></div></div>{filtered.length?<div className="cards">{filtered.map(recipe=><article className="card" key={recipe.id}><Link className="card-link" to={`/recipes/${recipe.slug}`}><div className={`art ${recipe.meal.toLowerCase()}`}><span>{recipe.id}</span></div><div className="card-body"><div className="meta"><span>{recipe.meal}</span><span>Ingredient-verified</span></div><h2>{recipe.title}</h2><p>{recipe.description}</p><div className="macros"><b>{recipe.calories} kcal</b><span>{recipe.protein} P</span><span>{recipe.carbs} C</span><span>{recipe.fat} F</span></div></div></Link><button type="button" className="favourite" onClick={()=>toggleFavourite(recipe.id)} aria-pressed={favourites.includes(recipe.id)} aria-label={`${favourites.includes(recipe.id)?'Remove':'Add'} ${recipe.title} ${favourites.includes(recipe.id)?'from':'to'} favourites`}>{favourites.includes(recipe.id)?'★':'☆'}</button></article>)}</div>:<EmptyState title="No recipes match">Clear the search or change filters.</EmptyState>}</>}

createRoot(document.getElementById('root')).render(<React.StrictMode><ErrorBoundary><HashRouter><Layout/></HashRouter></ErrorBoundary></React.StrictMode>);
